- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - cns_values.yaml
  vars:
    daemon_json:
      default-runtime: nvidia
      runtimes:
        nvidia:
          path: /usr/bin/nvidia-container-runtime
          runtimeArgs: []
  tasks:

    - name: Check docker is installed
      shell: docker
      register: docker_exists
      no_log: true
      failed_when: false

    - name: Check NVIDIA docker is installed
      shell: nvidia-docker
      register: nvidia_docker_exists
      no_log: true
      failed_when: false

    - name: Install Docker Dependencies on Ubuntu
      when: docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu' or nvidia_docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu'
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          - apt-utils
          - unzip
        state: latest
        update_cache: true

    - name: Install Docker Dependencies on RHEL
      when: docker_exists.rc >= 1 and ansible_distribution == 'RedHat' or nvidia_docker_exists.rc >= 1 and ansible_distribution == 'RedHat'
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - unzip
        state: latest
        update_cache: true

    - name: create docker.asc file
      when: docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu'
      become: true
      file: 
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'
        state: touch

    - name: Add Docker APT signing key
      when: docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu'
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        keyring: /etc/apt/keyrings/docker.asc
        state: present

    - name: Add Docker repository into sources list
      when: docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu'
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Add Docker repo on RHEL
      when: docker_exists.rc >= 1 and ansible_distribution == 'RedHat'
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Create docker systemd file
      when: docker_exists.rc >= 1 and microk8s == true
      become: true
      copy:
        dest: /lib/systemd/system/docker.service
        content: |
          [Unit]
          Description=Docker Application Container Engine
          Documentation=https://docs.docker.com
          After=network-online.target docker.socket firewalld.service snap.microk8s.daemon-containerd.service
          Wants=network-online.target
          Requires=docker.socket snap.microk8s.daemon-containerd.service

          [Service]
          Type=notify
          ExecStart=/usr/bin/dockerd -H unix:// --containerd=/var/snap/microk8s/common/run/containerd.sock
          ExecReload=/bin/kill -s HUP $MAINPID
          TimeoutSec=0
          RestartSec=2
          Restart=always
          StartLimitBurst=3
          StartLimitInterval=60s
          LimitNOFILE=infinity
          LimitNPROC=infinity
          LimitCORE=infinity
          TasksMax=infinity
          Delegate=yes
          KillMode=process
          OOMScoreAdjust=-500
          [Install]
          WantedBy=multi-user.target

    - name: Create docker systemd file
      when: docker_exists.rc >= 1 and microk8s == false
      become: true
      copy:
        dest: /etc/systemd/system/docker.service
        content: |
          [Unit]
          Description=Docker Application Container Engine
          Documentation=https://docs.docker.com
          After=network-online.target docker.socket firewalld.service containerd.service
          Wants=network-online.target
          Requires=docker.socket containerd.service

          [Service]
          Type=notify
          ExecStart=/usr/bin/dockerd -H unix:// --containerd=/run/containerd/containerd.sock
          ExecReload=/bin/kill -s HUP $MAINPID
          TimeoutSec=0
          RestartSec=2
          Restart=always
          StartLimitBurst=3
          StartLimitInterval=60s
          LimitNOFILE=infinity
          LimitNPROC=infinity
          LimitCORE=infinity
          TasksMax=infinity
          Delegate=yes
          KillMode=process
          OOMScoreAdjust=-500
          [Install]
          WantedBy=multi-user.target

    - name: Install Docker on Ubuntu
      when: docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu' and microk8s == false
      package:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: latest

    - name: Install Docker on Ubuntu
      when: docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu' and microk8s == true
      package:
        name: ['docker-ce', 'docker-ce-cli']
        state: latest

    - name: Install Docker on RHEL
      when: docker_exists.rc >= 1 and ansible_distribution == 'RedHat'
      yum:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: latest
        allowerasing: true
        update_cache: true

    - name: remove nvidia-docker on RHEL
      when: nvidia_docker_exists.rc == 0 and ansible_distribution == 'RedHat'
      yum:
        name:
          - nvidia-docker
          - nvidia-docker2
        state: absent
        autoremove: yes

    - name: remove nvidia-docker v1
      when: nvidia_docker_exists.rc == 0 and ansible_distribution == 'Ubuntu'
      apt:
        name: nvidia-docker
        state: absent
        purge: yes

    - name: Add NVIDIA Docker apt signing key for Ubuntu
      when: nvidia_docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu'
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        keyring: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        state: present

    - name: Get NVIDIA Container Toolkit Apt list
      when: nvidia_docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu'
      apt_repository:
        repo: "{{ item }}"
        state: present
        filename: libnvidia-container.list
      with_items:
        - deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
        - deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /

    - name: add NVIDIA Container Toolkit repo on RHEL
      when: nvidia_docker_exists.rc >= 1 and ansible_distribution == 'RedHat'
      get_url:
        url:   https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo 
        dest: /etc/yum.repos.d/nvidia-container-toolkit.repo
        mode: 0644
        owner: root
        group: root

    - name: Remove old nvidia container tooklit
      when: nvidia_docker_exists.rc >= 1
      failed_when: false
      apt:
        name: ['nvidia-container-toolkit*', 'nvidia-container-runtime*', 'libnvidia-container*']
        state: absent
        autoremove: yes

    - name: Install NVIDIA Docker and NVIDIA Container Runtime
      when: nvidia_docker_exists.rc >= 1 and ansible_distribution == 'Ubuntu'
      apt:
        name: ['nvidia-container-toolkit={{ nvidia_container_toolkit_version }}-1', 'nvidia-container-toolkit-base={{ nvidia_container_toolkit_version }}-1', 'libnvidia-container-tools={{ nvidia_container_toolkit_version }}-1', 'libnvidia-container1={{ nvidia_container_toolkit_version }}-1']
        state: present
        update_cache: true

    - name: install NVIDIA container runtime and NVIDIA Docker on RHEL
      when: nvidia_docker_exists.rc >= 1 and cns_version >= 10.0 and ansible_distribution == 'RedHat'
      yum:
        name: ['nvidia-container-toolkit', 'nvidia-docker2']
        state: present
        update_cache: yes

    - name: Update docker default runtime
      when: nvidia_docker_exists.rc >= 1
      copy:
        content: "{{ daemon_json | to_nice_json }}"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644

    - name: Update Containerd Runtime for NVIDIA Cloud Native Stack
      become: true
      block:
        - name: Create /etc/containerd
          file:
            path: /etc/containerd
            state: directory

        - name: Write defaults to config.toml
          copy:
            src: "{{lookup('pipe', 'pwd')}}/files/config.toml"
            dest: /etc/containerd/config.toml
            mode: 0664

        - name: Enable systemd cgroups
          shell: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

        - name: restart containerd
          systemd_service:
            name: containerd
            state: restarted
            daemon_reload: yes
      when: "container_runtime == 'containerd' and microk8s == false"

    - name: Create "docker" group
      when: docker_exists.rc >= 1
      become: true
      group:
        name: docker
        state: present

    - name: Add remote "ubuntu" user to "docker" group
      when: docker_exists.rc >= 1
      become: true
      user:
        name: "{{ ansible_user_id }}"
        group: docker
        append: yes

    - name: Configure CDI
      shell: nvidia-ctk runtime configure --runtime containerd --cdi.enabled --config /etc/containerd/config.toml; nvidia-ctk runtime configure --runtime docker --cdi.enabled; nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
      become: true
      when: nvidia_docker_exists.rc >= 1
      ignore_errors: true

    - name: NGC CLI Setup
      block:
        - name: Download CLI
          get_url:
            url: https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/3.51.0/files/ngccli_linux.zip
            dest: /tmp/ngccli_linux.zip
            mode: 0664

        - name: Install NGC CLI
          unarchive:
            src: /tmp/ngccli_linux.zip
            dest: "{{ ansible_user_dir }}"
            remote_src: yes

        - name: change ngc file permission
          file:
            path: "{{ ansible_user_dir }}/ngc-cli/ngc"
            mode: '0777'

        - name: Add Path to bashrc
          lineinfile:
            path: "{{ ansible_user_dir }}/.bashrc"
            insertafter: '^PATH='
            line: 'PATH=$PATH:{{ ansible_user_dir }}/ngc-cli'
            state: present